### ISSUE TITLE
Current build failing?

### ISSUE THREAD

**Issue by dit7ya** [foo-dogsquared/nix-overlay-guix#9]
**Describe the bug**
Currently the build fails (due to two tests of the `guile-ssh` package not passing).

This is visible from the last CI run itself - https://github.com/foo-dogsquared/nix-overlay-guix/actions/runs/3416120664/jobs/5685940330

**Comment by foo-dogsquared** [comment]
This sounds similar to issues #5 and #6. You might to try out [the workaround posted](https://github.com/foo-dogsquared/nix-overlay-guix/issues/6#issuecomment-1308695522) in those issues.

Here's the exact quote:

> To reiterate, the problem is the version of libssh in the unstable branch is not compatible with guile-ssh which I assume you're using the overlay from this flake. It only works on 22.05 stable branch for now. As a workaround, you'll have to remove the overlay, make sure the Guix overlay flake follows nixpkgs 22.05 branch, and point `services.guix.package` to the package that came with this flake (for example, `services.guix.package = inputs.guix-overlay.packages.x86_64-linux.guix`).

**Comment by dit7ya** [comment]
Sorry, I somehow missed those issues. Thanks.
